server:
  port: 8083
application:
  filePath: file
  corpId: wx1575c3f8d572890d
  corpSecret: P8mS9dDsgD3YNOH5EB3IC8cbpXaHLdQXHJebb81i_Fo
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3305/wxj_test?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.current_session_context_class: thread



