server:
  port: 8083
application:
  filePath: file
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.10.125:3306/wxj_test2?characterEncoding=utf-8
    username: jq
    password: jq
    tomcat:
      validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.current_session_context_class: thread



